// Completeness / soundness test against GENUINE tilings.
// 1. A genuine hat tiling patch is generated by the hat substitution system (gen_hat_patch.js, hatviz code).
// 2. Every hat is matched to our Tile(1,√3) (up to rotation/reflection), and the patch is converted to a tiling by Tile(a,b), (a,b)=(299,240),
//    using the grading of tile vertices by (a-edges, b-edges) (parent theorem 6.1: combinatorially equivalent tilings).  Consistency is checked exactly.
// 3. Each Tile(299,240) is cut into its 5 pieces (d = 208): a genuine tiling by T0, T1 and mirror images.
// 4. For interior pieces, the TRUE first corona (engine-style closure) is mapped to the reference position and looked up among the engine's
//    first coronas and among its pruning survivors.  A true corona that is NOT a survivor would invalidate the pruning argument.
// Usage: AB=299,240,208 node real_tilings.js patch.json [maxCores]
import { readFileSync } from 'fs';
import { E, cadd, csub, cmul, cscale, cconj, ceq, ckey } from '../exact/field4.js';
import { buildExact, mirrorPoly } from '../exact/ab_exact.js';
import { Tile, makeKind, growCorona, growLayer, wedgeAt, cf, lenOf, interiorsOverlap, polyKey } from '../exact/engine.js';

const hats = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const MAXCORES = Number(process.argv[3] || 400);
const R = (p, q = 1) => E.rat(p, q), half = R(1, 2), s3h = E.s3(1, 2), Z = E.int(0), O1 = E.int(1);
const c30 = [O1, s3h, half, Z, half.neg(), s3h.neg(), O1.neg(), s3h.neg(), half.neg(), Z, half, s3h];
const s30 = [Z, half, s3h, O1, s3h, half, Z, half.neg(), s3h.neg(), O1.neg(), s3h.neg(), half.neg()];
const rotK = (z, k) => cmul(z, [c30[k], s30[k]]);
const gmap = (z, r, k) => rotK(r ? cconj(z) : z, k);
const withAB = (ab) => { const old = process.env.AB; process.env.AB = ab; const x = buildExact(); process.env.AB = old; return x; };

// ---- graded vertices of Tile(a,b): V = a*VA + b*VB
const V21 = withAB('2,1,1').N.slice(0, 14), V12 = withAB('1,2,1').N.slice(0, 14);   // V(a,b) is linear in (a,b): solve for the a- and b-parts
const third = R(1, 3), two = R(2);
const VA = V21.map((z, i) => cscale(csub(cscale(z, two), V12[i]), third)), VB = V12.map((z, i) => cscale(csub(cscale(z, two), V21[i]), third));
const sq3 = Math.sqrt(3);
const f2 = (z) => [z[0].f(), z[1].f()];
const V1f = VA.map((z, i) => { const a = f2(z), b = f2(VB[i]); return [a[0] + sq3 * b[0], a[1] + sq3 * b[1]]; });
console.log("V1f",V1f.map(p=>p.map(x=>x.toFixed(2)).join(",")).join(" | "));
const A = 299, B = 240;
const { N: Nact, pieces } = (() => { const o = process.env.AB; process.env.AB = '299,240,208'; const x = buildExact(); process.env.AB = o; return x; })();
const Vact = Nact.slice(0, 14);

// ---- hat outline (hatviz) and placements
const r3h = Math.sqrt(3) / 2, hexPt = (x, y) => [x + 0.5 * y, r3h * y];
const hatOutline = [[0,0],[-1,-1],[0,-2],[2,-2],[2,-1],[4,-2],[5,-1],[4,0],[3,0],[2,2],[0,3],[0,2],[-1,2]].map(([x, y]) => hexPt(x, y));
const COLLINEAR = 6; // index of the 180-degree vertex of our 14-gon
// hatviz places hats at scale 1/2 (edges 1/2 and sqrt3/2); rescale the whole patch by 1/scale so that hats have edges 1 and sqrt3
const scale = Math.sqrt(Math.abs(hats[0].m[0] * hats[0].m[4] - hats[0].m[1] * hats[0].m[3]));
console.log('hat scale in patch:', scale.toFixed(6));
const place = hats.map((h) => hatOutline.map(([x, y]) => [(h.m[0] * x + h.m[1] * y + h.m[2]) / scale, (h.m[3] * x + h.m[4] * y + h.m[5]) / scale]));
const close = (p, q) => Math.hypot(p[0] - q[0], p[1] - q[1]) < 1e-6;
const cosk = (k) => Math.cos(k * Math.PI / 6), sink = (k) => Math.sin(k * Math.PI / 6);
const placement = place.map((hp, hi) => {
  for (const r of [0, 1]) for (let k = 0; k < 12; k++) {
    const W = V1f.map(([x, y]) => { const yy = r ? -y : y; return [x * cosk(k) - yy * sink(k), x * sink(k) + yy * cosk(k)]; });
    for (const hpt of hp) {
      const T = [hpt[0] - W[0][0], hpt[1] - W[0][1]];
      if (W.every((w, i) => i === COLLINEAR || hp.some((q) => close([w[0] + T[0], w[1] + T[1]], q)))) return { hi, r, k, T, W: W.map((w) => [w[0] + T[0], w[1] + T[1]]) };
    }
  }
  throw new Error('hat ' + hi + ' does not match Tile(1,sqrt3)');
});
console.log(`matched ${placement.length} hats to Tile(1,√3); reflected: ${placement.filter((p) => p.r).length}`);

// ---- grading: BFS over shared vertices
const hk = (p) => Math.round(p[0] * 1e4) + ',' + Math.round(p[1] * 1e4);
const at = new Map();
placement.forEach((p, t) => p.W.forEach((w, i) => { if (i === COLLINEAR) return; const k = hk(w); (at.get(k) || at.set(k, []).get(k)).push([t, i]); }));
const gv = (t, i) => { const p = placement[t]; return [gmap(VA[i], p.r, p.k), gmap(VB[i], p.r, p.k)]; }; // graded vertex relative to translation
const G = new Array(placement.length).fill(null); G[0] = [[Z, Z], [Z, Z]];
const gpos = (t, i) => { const g = gv(t, i); return [cadd(G[t][0], g[0]), cadd(G[t][1], g[1])]; };
const queue = [0];
while (queue.length) {
  const t = queue.shift();
  placement[t].W.forEach((w, i) => {
    if (i === COLLINEAR) return;
    const P = gpos(t, i);
    for (const [u, j] of at.get(hk(w))) if (G[u] === null) { const g = gv(u, j); G[u] = [csub(P[0], g[0]), csub(P[1], g[1])]; queue.push(u); }
  });
}
const unplaced = G.filter((x) => x === null).length;
console.log(`graded translations assigned: ${G.length - unplaced} of ${G.length}`);
if (unplaced) throw new Error('patch not connected through shared vertices');
let incons = 0;
for (const lst of at.values()) { const P0 = gpos(lst[0][0], lst[0][1]); for (const [u, j] of lst.slice(1)) { const P = gpos(u, j); if (!ceq(P[0], P0[0]) || !ceq(P[1], P0[1])) incons++; } }
console.log(`grading consistency violations at shared vertices: ${incons}`);
if (incons) throw new Error('inconsistent grading');

// ---- actual tiles Tile(299,240) and pieces
const ex = (p) => [R(A), R(B)];
const aE = R(A), bE = R(B);
const tileOrigin = G.map(([ta, tb]) => cadd(cscale(ta, aE), cscale(tb, bE)));
const kinds = { P: makeKind('P', pieces.A), Pb: makeKind('Pb', mirrorPoly(pieces.A)), H: makeKind('H', pieces.H), Hb: makeKind('Hb', mirrorPoly(pieces.H)) };
const unit = (ev) => cscale(ev, lenOf(ev).inv());
// standard-frame polygons for r=0/1 (ccw), the kind they are, and the cyclic shift s with kind.poly[j] -> poly[(s+j)%n] by a proper motion
function congruence(src, dst) {
  const n = src.length; if (dst.length !== n) return null;
  for (let s = 0; s < n; s++) {
    const a0 = src[0], a1 = src[1], b0 = dst[s], b1 = dst[(s + 1) % n];
    const ea = csub(a1, a0), eb = csub(b1, b0);
    if (!lenOf(ea).eq(lenOf(eb))) continue;
    const rot = cmul(unit(eb), cconj(unit(ea)));
    const g = (p) => cadd(b0, cmul(rot, csub(p, a0)));
    if (src.every((p, i) => ceq(g(p), dst[(s + i) % n]))) return s;
  }
  return null;
}
const stdInfo = {};
for (const L of ['A', 'B', 'C', 'D', 'H']) for (const r of [0, 1]) {
  const poly = r ? pieces[L].map(cconj).reverse() : pieces[L];
  let found = null;
  for (const kn of Object.keys(kinds)) { const s = congruence(kinds[kn].poly, poly); if (s !== null) { found = { kn, s }; break; } }
  if (!found) throw new Error(`piece ${L} r=${r} matches no kind`);
  stdInfo[L + r] = found;
}
console.log('piece kinds (r=0):', ['A','B','C','D','H'].map((L) => `${L}:${stdInfo[L + 0].kn}`).join(' '), ' (r=1):', ['A','B','C','D','H'].map((L) => `${L}:${stdInfo[L + 1].kn}`).join(' '));
const tiles = []; // {t: Tile, L, hat, kn, s, dst}
placement.forEach((p, hi) => {
  const org = tileOrigin[hi];
  for (const L of ['A', 'B', 'C', 'D', 'H']) {
    let poly = pieces[L].map((z) => cadd(org, gmap(z, p.r, p.k)));
    if (p.r) poly = poly.reverse();
    const { kn, s } = stdInfo[L + p.r], n = poly.length;
    const O = poly[s], g0 = unit(csub(poly[(s + 1) % n], O));
    const t = new Tile(kinds[kn], 0, O, g0);
    tiles.push({ t, L, hat: hi, kn, s, dst: poly });
  }
});
console.log(`pieces: ${tiles.length}`);
if (process.env.DRAW) { // optional picture of the patch: pieces coloured by kind, parent Tile(a,b) outlines in black
  const { writeFileSync } = await import('fs');
  const col = { P: '#e8a33d', Pb: '#4a90c2', H: '#c4c4c4', Hb: '#c4c4c4' };
  const pts = tiles.flatMap((x) => x.t.fpts); const x0 = Math.min(...pts.map((p) => p[0])), x1 = Math.max(...pts.map((p) => p[0])), y0 = Math.min(...pts.map((p) => p[1])), y1 = Math.max(...pts.map((p) => p[1]));
  const W = 1000, sc = W / (x1 - x0), Hh = (y1 - y0) * sc;
  const tr = (p) => `${((p[0] - x0) * sc).toFixed(1)},${((y1 - p[1]) * sc).toFixed(1)}`;
  let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${Hh.toFixed(0)}" viewBox="0 0 ${W} ${Hh.toFixed(0)}"><rect width="100%" height="100%" fill="#fff"/>`;
  for (const x of tiles) svg += `<polygon points="${x.t.fpts.map(tr).join(' ')}" fill="${col[x.kn]}" stroke="#555" stroke-width="0.6"/>`;
  placement.forEach((p, hi) => { const org = tileOrigin[hi]; const outline = Vact.map((z) => cf(cadd(org, gmap(z, p.r, p.k)))).filter((_, i) => i !== COLLINEAR); svg += `<polygon points="${outline.map(tr).join(' ')}" fill="none" stroke="#000" stroke-width="2.2" stroke-linejoin="round"/>`; });
  writeFileSync(process.env.DRAW, svg + '</svg>'); console.log('drew', process.env.DRAW);
}

// ---- reference coronas (first coronas and survivors) for the 4 kinds
const refPoly = { P: pieces.A, Pb: mirrorPoly(pieces.A), H: pieces.H, Hb: mirrorPoly(pieces.H) };
const first = {}, surv = {};
for (const kn of Object.keys(kinds)) {
  const ref = new Tile(kinds[kn], 0, refPoly[kn][0], kinds[kn].corners[0].start);
  const { results } = growCorona(ref, kinds, {});
  first[kn] = new Set(results.map((st) => st.tiles.map((x) => x.key).sort().join('|')));
  surv[kn] = new Set();
  for (const st of results) {
    let dead = false;
    for (let i = 0; i < st.tiles.length && !dead; i++) { const r = growLayer(st, [st.tiles[i]], kinds, { maxNodes: 30000 }); if (!r.truncated && !r.results.length) dead = true; }
    if (!dead) surv[kn].add(st.tiles.map((x) => x.key).sort().join('|'));
  }
  console.log(`reference ${kn}: ${first[kn].size} first coronas, ${surv[kn].size} survivors`);
}

// ---- true coronas of interior pieces
const hatC = place.map((hp) => [hp.reduce((s, q) => s + q[0], 0) / hp.length, hp.reduce((s, q) => s + q[1], 0) / hp.length]);
const cx = hatC.reduce((s, q) => s + q[0], 0) / hatC.length, cy = hatC.reduce((s, q) => s + q[1], 0) / hatC.length;
const rad = Math.max(...hatC.map((q) => Math.hypot(q[0] - cx, q[1] - cy)));
// interior = the disc of radius RDISC around the hat centre is entirely covered by hats of the patch (so the true corona is complete)
const RDISC = Number(process.env.RDISC || 9);
const cell = 8, grid = new Map();
place.forEach((hp, i) => { const k = Math.floor(hatC[i][0] / cell) + ',' + Math.floor(hatC[i][1] / cell); (grid.get(k) || grid.set(k, []).get(k)).push(i); });
const inPoly = (p, poly) => { let c = false; for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) { const [xi, yi] = poly[i], [xj, yj] = poly[j]; if ((yi > p[1]) !== (yj > p[1]) && p[0] < ((xj - xi) * (p[1] - yi)) / (yj - yi) + xi) c = !c; } return c; };
const covered = (p) => { const gx = Math.floor(p[0] / cell), gy = Math.floor(p[1] / cell); for (let dx = -2; dx <= 2; dx++) for (let dy = -2; dy <= 2; dy++) for (const i of grid.get((gx + dx) + ',' + (gy + dy)) || []) if (inPoly(p, place[i])) return true; return false; };
const hatInterior = place.map((_, i) => { for (let a = 0; a < 16; a++) if (!covered([hatC[i][0] + RDISC * Math.cos(a * Math.PI / 8), hatC[i][1] + RDISC * Math.sin(a * Math.PI / 8)])) return false; return true; });
const interior = tiles.filter((x) => hatInterior[x.hat]);
console.log(`patch radius ${rad.toFixed(1)}; interior pieces: ${interior.length} of ${tiles.length}`);
const bb = tiles.map((x) => x.t.bb);
const near = (X, Y) => !(X.bb[2] < Y.bb[0] - 1e-6 || Y.bb[2] < X.bb[0] - 1e-6 || X.bb[3] < Y.bb[1] - 1e-6 || Y.bb[3] < X.bb[1] - 1e-6);
let total = 0, inFirst = 0, inSurv = 0, bad = 0, overlaps = 0; const byKind = {}, rolesSeen = {};
const sample = interior.length > MAXCORES ? interior.filter((_, i) => i % Math.ceil(interior.length / MAXCORES) === 0) : interior;
const seenCoronas = new Map(), unionSeen = {};
for (const core of sample) {
  const cand = tiles.filter((x) => x !== core && near(core.t, x.t));
  const S = [core], nb = [];
  for (let changed = true; changed;) {
    changed = false;
    for (const x of cand) {
      if (nb.includes(x)) continue;
      const hit = x.t.pts.some((p) => wedgeAt(core.t, p, cf(p)) !== null && S.some((y) => y.t.pts.some((q) => ceq(p, q))));
      if (hit) { nb.push(x); S.push(x); changed = true; }
    }
  }
  for (let i = 0; i < S.length; i++) for (let j = i + 1; j < S.length; j++) if (interiorsOverlap(S[i].t, S[j].t)) overlaps++;
  // map the core to the reference position
  const kn = core.kn, poly = kinds[kn].poly, n = core.dst.length, s = core.s;
  const ea = csub(poly[1], poly[0]), eb = csub(core.dst[(s + 1) % n], core.dst[s]);
  const rot = cmul(unit(ea), cconj(unit(eb))), mv = (p) => cadd(poly[0], cmul(rot, csub(p, core.dst[s])));
  const keys = S.map((x) => polyKey(x.t.pts.map(mv))).sort().join('|');
  const refKey = (() => { const rk = new Tile(kinds[kn], 0, poly[0], kinds[kn].corners[0].start).key; return rk; })();
  // engine keys are Tile.key = sorted vertex keys joined by ';' -- same as polyKey
  total++; byKind[kn] = (byKind[kn] || 0) + 1;
  const mirrored = (kn === 'Pb' || kn === 'Hb') ? S.map((x) => polyKey(x.t.pts.map(mv).map(([px, py]) => [px.neg(), py]))).sort().join('|') : keys;
  const base = kn === 'P' || kn === 'Pb' ? 'T1' : 'T0';
  if ((kn === 'Pb' || kn === 'Hb') && !surv[kn === 'Pb' ? 'P' : 'H'].has(mirrored)) console.log('mirror of a Pb/Hb true corona is not a P/H survivor!');
  (unionSeen[base] = unionSeen[base] || new Set()).add(mirrored);
  const f = first[kn].has(keys), sv = surv[kn].has(keys);
  if (f) inFirst++; if (sv) inSurv++;
  if (!sv) { bad++; console.log(`NOT A SURVIVOR: core ${core.L} (kind ${kn}), ${S.length} tiles; in first coronas: ${f}`); }
  seenCoronas.set(kn + '#' + keys, (seenCoronas.get(kn + '#' + keys) || 0) + 1);
}
console.log(`true coronas checked: ${total} (${JSON.stringify(byKind)}); distinct: ${seenCoronas.size}`);
for (const kn of Object.keys(kinds)) { const d = [...seenCoronas.keys()].filter((k) => k.startsWith(kn + '#')).length; console.log(`  kind ${kn}: ${d} distinct true coronas realised, of ${surv[kn].size} survivors`); }
console.log(`  mirror-identified (reflected cases folded onto unreflected): T1 ${unionSeen.T1?.size} of ${surv.P.size} survivors realised; T0 ${unionSeen.T0?.size} of ${surv.H.size}`);
console.log(`  found among engine first coronas: ${inFirst}; found among pruning survivors: ${inSurv}; NOT survivors: ${bad}; overlapping tile pairs inside coronas: ${overlaps}`);
console.log(bad === 0 && overlaps === 0 ? 'REAL-TILING TEST PASSED' : 'REAL-TILING TEST FAILED');
